on: [push]

name: CI

jobs:
  test:
    name: Build and test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: test
        run: cargo test
